# Generated by Django 4.1.13 on 2024-06-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_post_likes_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
